version: '3.8'
services:
  dev-db:
    image: postgres:16
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Krutik@30
      POSTGRES_DB: nest-auth
    networks:
      - nestjs
  test-db:
    image: postgres:16
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Krutik@30
      POSTGRES_DB: nest-auth
    networks:
      - nestjs
networks:
  nestjs:
